name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest

    env:
      MY_SECRET: ${{ secrets.APP_ID }}
      MY_VAR: ${{ vars.APP_ID_VAR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World"

      - name: Print Variable
        run: echo "Variable value is $MY_VAR"

      - name: Print Secret
        run: echo "Secret value is $MY_SECRET"
